# Generated by Django 5.2.4 on 2025-07-07 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('acao', models.CharField(max_length=100)),
                ('entidade', models.CharField(max_length=100)),
                ('id_entidade', models.CharField(max_length=50)),
                ('descricao', models.TextField()),
            ],
        ),
    ]
