# Generated by Django 5.2.4 on 2025-07-07 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Internacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_entrada', models.DateTimeField()),
                ('data_saida', models.DateTimeField(blank=True, null=True)),
                ('motivo', models.CharField(max_length=255)),
                ('observacoes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Leito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10)),
                ('tipo', models.CharField(max_length=50)),
                ('ala', models.CharField(max_length=100)),
                ('disponivel', models.BooleanField(default=True)),
            ],
        ),
    ]
