# Generated by Django 5.2.4 on 2025-07-07 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('internacoes', '0002_initial'),
        ('profissionais', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='internacao',
            name='profissional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profissionais.profissionalsaude'),
        ),
        migrations.AddField(
            model_name='internacao',
            name='leito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='internacoes.leito'),
        ),
    ]
