# Generated by Django 5.2.4 on 2025-07-07 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agendamentos', '0002_initial'),
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teleconsulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateTimeField()),
                ('fim', models.DateTimeField(blank=True, null=True)),
                ('url_video', models.URLField()),
                ('status', models.CharField(choices=[('agendada', 'Agendada'), ('em_andamento', 'Em andamento'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada')], default='agendada', max_length=20)),
                ('token_acesso', models.CharField(max_length=255)),
                ('consulta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='agendamentos.consulta')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacientes.paciente')),
            ],
        ),
    ]
