# Generated by Django 5.2.4 on 2025-07-05 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0001_initial'),
        ('profissionais', '0001_initial'),
        ('telemedicina', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teleconsulta',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacientes.paciente'),
        ),
        migrations.AddField(
            model_name='teleconsulta',
            name='profissional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profissionais.profissionalsaude'),
        ),
    ]
