# Generated by Django 5.2.4 on 2025-07-06 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='perfil',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.PROTECT, to='usuarios.perfilusuario'),
            preserve_default=False,
        ),
    ]
