# Generated by Django 5.2.4 on 2025-07-05 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('mensagem', models.TextField()),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('lida', models.BooleanField(default=False)),
                ('tipo', models.CharField(choices=[('sistema', 'Sistema'), ('consulta', 'Consulta'), ('receita', 'Receita'), ('outro', 'Outro')], max_length=50)),
                ('canal', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('app', 'Aplicativo')], max_length=50)),
            ],
        ),
    ]
